"""Generate the paper's LaTeX result tables directly from run outputs.

The tables are emitted from checkpoints/*/results.json rather than typed by
hand. Every number in the paper therefore has exactly one source, and a
rerun or an added seed regenerates the tables instead of requiring a manual
edit that can silently disagree with the runs.

Usage:
    python analysis/make_tables.py [--out paper/tables]
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import statistics as st
from typing import Dict, List, Sequence, Tuple

CORPORA: Tuple[str, ...] = ("IEMO", "SAMSEMO")
CORPUS_LABEL: Dict[str, str] = {
    "IEMO": "IEMOCAP",
    "SAMSEMO": "SAMSEMO",
    "MSPI": "MSP-Improv",
    "CMUMOSEI": "CMU-MOSEI",
}
METRIC_LABEL: Dict[str, str] = {
    "uar": "UAR",
    "neutral_auc": "AUC$_{\\mathrm{neu}}$",
    "emo_auc": "AUC$_{\\mathrm{emo}}$",
    "f1_weighted": "WF1",
}

Runs = Dict[str, Dict[str, Dict[str, float]]]


def load_arm(*arms: str) -> Runs:
    """Load per-seed, per-corpus test metrics for one logical arm.

    An arm may be spread over several experiment names when seeds were added
    in a later batch (for example cw_sqrt_base and cw_sqrt_base_more).

    Args:
        arms: Experiment names whose checkpoint directories are merged.

    Returns:
        Mapping of seed -> corpus -> metric name -> value.
    """
    out: Runs = {}
    for arm in arms:
        for path in sorted(glob.glob(f"checkpoints/{arm}_seed*/results.json")):
            seed = os.path.basename(os.path.dirname(path)).split("seed")[-1]
            with open(path) as handle:
                payload = json.load(handle)
            out[seed] = {e["dataset"]: e["results"] for e in payload["test_results"]}
    return out


def paired(a: Runs, b: Runs, corpus: str, metric: str,
           seeds: Sequence[str]) -> Tuple[float, float, float, int]:
    """Paired per-seed difference between two arms, scaled by 100.

    Args:
        a: Arm whose value is the minuend.
        b: Arm whose value is the subtrahend.
        corpus: Test corpus key.
        metric: Metric key inside the corpus results.
        seeds: Seeds present in both arms, in a fixed order.

    Returns:
        Tuple of (mean difference, sample sd, paired t statistic, win count).
    """
    diffs = [100.0 * (a[s][corpus][metric] - b[s][corpus][metric]) for s in seeds]
    mean = st.mean(diffs)
    sd = st.stdev(diffs) if len(diffs) > 1 else 0.0
    t = mean / (sd / len(diffs) ** 0.5) if sd else float("nan")
    return mean, sd, t, sum(1 for d in diffs if d > 0)


def common_seeds(*arms: Runs) -> List[str]:
    """Seeds present in every supplied arm, ordered numerically."""
    shared = set(arms[0])
    for arm in arms[1:]:
        shared &= set(arm)
    return sorted(shared, key=int)


def absolute_table(arms: Dict[str, Runs], seeds: Sequence[str]) -> str:
    """Build the raw per-corpus, per-arm results table.

    Absolute values with the between-seed standard deviation, because the
    operating point matters and deltas alone hide it.

    Args:
        arms: Ordered mapping of display name -> arm runs.
        seeds: Seeds to average over.

    Returns:
        LaTeX tabular source.
    """
    metrics = ("uar", "neutral_auc", "emo_auc", "f1_weighted")
    lines = [
        "% Generated by analysis/make_tables.py - do not edit by hand.",
        "\\begin{tabular}{ll" + "r" * len(metrics) + "}",
        "\\toprule",
        "Corpus & System & " + " & ".join(METRIC_LABEL[m] for m in metrics) + " \\\\",
        "\\midrule",
    ]
    for corpus in CORPORA:
        for i, (name, arm) in enumerate(arms.items()):
            cells = []
            for metric in metrics:
                vals = [100.0 * arm[s][corpus][metric] for s in seeds]
                sd = st.stdev(vals) if len(vals) > 1 else 0.0
                cells.append(f"{st.mean(vals):.2f} \\scriptsize{{({sd:.2f})}}")
            head = CORPUS_LABEL[corpus] if i == 0 else ""
            lines.append(f"{head} & {name} & " + " & ".join(cells) + " \\\\")
        lines.append("\\midrule" if corpus != CORPORA[-1] else "\\bottomrule")
    lines.append("\\end{tabular}")
    return "\n".join(lines)


def stars(t_stat: float, n: int) -> str:
    """Significance marker for a paired t statistic.

    Args:
        t_stat: Paired t statistic.
        n: Number of paired seeds.

    Returns:
        LaTeX superscript marker, empty when not significant at 0.05.
    """
    if n < 3:
        return ""
    crit = {3: (4.303, 9.925), 4: (3.182, 5.841), 5: (2.776, 4.604)}
    lo, hi = crit.get(n, (2.776, 4.604))
    a = abs(t_stat)
    if a >= hi:
        return "$^{\\dagger\\dagger}$"
    if a >= lo:
        return "$^{\\dagger}$"
    return ""


def cell(arm: Runs, corpus: str, metric: str, seeds: Sequence[str]) -> str:
    """Format one raw mean with its between-seed standard deviation.

    One definition of spread is used in every table: the standard deviation of
    the metric across seeds within that arm. A paired standard deviation would
    be a smaller and arguably more relevant number, since arms are compared per
    seed and most seed-to-seed variation is shared, but mixing the two in
    identically formatted parentheses reads as inconsistent. The paired figure
    belongs in the results text, and significance is carried by the markers.

    Args:
        arm: Arm whose values are summarised.
        corpus: Test corpus key.
        metric: Metric key.
        seeds: Seeds to average over.

    Returns:
        LaTeX cell text.
    """
    vals = [100.0 * arm[s][corpus][metric] for s in seeds]
    sd = st.stdev(vals) if len(vals) > 1 else 0.0
    return f"{st.mean(vals):.2f} \\scriptsize{{({sd:.2f})}}"


def contrast_table(res: Runs, base: Runs, ctrl: Runs, seeds: Sequence[str]) -> str:
    """Build the three-arm comparison table in raw metric units.

    Reports absolute values with between-seed standard deviation rather than
    differences. Significance of the paired residual-against-control contrast
    is carried by a marker on the residual row, so the comparison stays
    visible without the table showing a delta.

    Args:
        res: Residual arm.
        base: No-auxiliary baseline.
        ctrl: Shuffled-target control.
        seeds: Seeds present in all three arms.

    Returns:
        LaTeX tabular source.
    """
    metrics = ("uar", "neutral_auc", "emo_auc", "f1_weighted")
    lines = [
        "% Generated by analysis/make_tables.py - do not edit by hand.",
        "\\begin{tabular}{ll" + "r" * len(metrics) + "}",
        "\\toprule",
        "Corpus & System & " + " & ".join(METRIC_LABEL[m] for m in metrics) + " \\\\",
        "\\midrule",
    ]
    arms = (("Baseline", base), ("Control (shuffled)", ctrl), ("Residual (ours)", res))
    for corpus in CORPORA:
        for i, (name, arm) in enumerate(arms):
            cells = []
            for metric in metrics:
                text = cell(arm, corpus, metric, seeds)
                if name.startswith("Residual"):
                    _, _, t_stat, _ = paired(res, ctrl, corpus, metric, seeds)
                    text += stars(t_stat, len(seeds))
                cells.append(text)
            head = CORPUS_LABEL[corpus] if i == 0 else ""
            lines.append(f"{head} & {name} & " + " & ".join(cells) + " \\\\")
        lines.append("\\midrule" if corpus != CORPORA[-1] else "\\bottomrule")
    lines.append("\\end{tabular}")
    return "\n".join(lines)


def ladder_table(base: Runs, rungs: Sequence[Tuple[str, str, Runs]]) -> str:
    """Build the auxiliary-target ablation ladder in raw metric units.

    Each rung adds one component to the auxiliary target. Values are absolute
    IEMOCAP scores with between-seed standard deviation; the marker records
    significance of that arm against the no-auxiliary baseline.

    Args:
        base: No-auxiliary baseline, shown as the first row.
        rungs: Sequence of (display name, target description, arm runs).

    Returns:
        LaTeX tabular source.
    """
    lines = [
        "% Generated by analysis/make_tables.py - do not edit by hand.",
        "\\begin{tabular}{llrr}",
        "\\toprule",
        "Auxiliary target & Information & UAR & AUC$_{\\mathrm{neu}}$ \\\\",
        "\\midrule",
    ]
    base_seeds = sorted(base, key=int)
    lines.append(
        "None (baseline) & --- & " + cell(base, "IEMO", "uar", base_seeds)
        + " & " + cell(base, "IEMO", "neutral_auc", base_seeds) + " \\\\")
    for name, info, arm in rungs:
        seeds = common_seeds(arm, base)
        cells = []
        for metric in ("uar", "neutral_auc"):
            _, _, t_stat, _ = paired(arm, base, "IEMO", metric, seeds)
            cells.append(cell(arm, "IEMO", metric, seeds)
                         + stars(t_stat, len(seeds)))
        lines.append(f"{name} & {info} & " + " & ".join(cells)
                     + f" \\\\  % n={len(seeds)}")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines)


def main() -> None:
    """Write every generated table into the output directory."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="paper/tables")
    args = parser.parse_args()
    os.makedirs(args.out, exist_ok=True)

    base = load_arm("cw_sqrt_base", "cw_sqrt_base_more")
    res = load_arm("cw_sqrt_res", "cw_sqrt_res_more")
    ctrl = load_arm("cw_sqrt_ctrl")
    seeds = common_seeds(base, res, ctrl)

    arms = {"Baseline": base, "Control (shuffled)": ctrl, "Residual (ours)": res}
    written = [
        ("results_main.tex", absolute_table(arms, seeds)),
        ("contrast.tex", contrast_table(res, base, ctrl, seeds)),
        ("ladder.tex", ladder_table(base, [
            ("Shuffled", "none", ctrl),
            ("Raw VAD", "VAD", load_arm("sens_rawvad_res")),
            ("Residual, unwhitened", "VAD $-$ centroid", load_arm("sens_euclid_res")),
            ("Residual, whitened (ours)",
             "(VAD $-$ centroid) / scatter", res),
        ])),
    ]
    for name, body in written:
        with open(os.path.join(args.out, name), "w") as handle:
            handle.write(body + "\n")
        print(f"wrote {os.path.join(args.out, name)}")
    print(f"seeds used for main tables: {seeds}")


if __name__ == "__main__":
    main()
